version: '3.3'
services:
  mongodb:
    image: mongo:3.2
    volumes:
      - mongodb:/data/db
    networks:
      - backnet

  rabbitmq:
    image: rabbitmq:management #3-managment
    ports: 
      - 15672:15672/tcp
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_LOGS=/var/log/rabbitmq/rabbit.log
    volumes:
      - rabbitdata:/var/lib/rabbitmq
      - rabbitlog:/var/log/rabbitmq
    networks:
      - backnet

  ui:
    image: j10i2/crawler-ui
    ports:
      - 8000:8000/tcp
    networks:
      - frontnet
      - backnet
    environment:
      - MONGO=mongodb
      - MONGO_PORT=27017
    depends_on:
      - mongodb

  app:
    image: vdaishi/crawler:1.0
    restart: always
    environment:
      - MONGO=mongodb
      - MONGO_PORT=27017
      - RMQ_HOST=rabbitmq
      - RMQ_QUEUE=urls
      - RMQ_USERNAME=guest
      - RMQ_PASSWORD=guest
      - CHECK_INTERVAL=20
      - EXCLUDE_URLS=".*github.com"
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - backnet

volumes:
  mongodb:
  rabbitdata:
  rabbitlog:

networks:
  backnet:
  frontnet:
