---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: crawler-ui
      labels:
        app: ui
        component: ui
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: ui
          component: ui
      template:
        metadata:
          name: ui
          labels:
            app: ui
            component: ui
        spec:
          containers:
          - image: j10i2/crawler-ui:1.1
            name: ui
            env:
             - name: MONGO
               value: "mongo"
             - name: MONGO_PORT
               value: "27017"
            ports:
             - containerPort: 8000
        